title: Kochbuch
baseurl: "/kochbuch"
url: "https://xamiax.github.io"

collections:
  rezepte:
    output: true
    permalink: /rezepte/:path/

include:
  - _rezepte/**/*.jpg
  - _rezepte/**/*.jpeg
  - _rezepte/**/*.png
  - _rezepte/**/*.webp
  - _rezepte/**/*.JPG
  - _rezepte/**/*.JPEG
  - _rezepte/**/*.PNG